#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2012-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys

if sys.version_info < (3, 7):
    raise RuntimeError(f'Python >= {3.7} is required')

import argparse
import dataclasses
import errno
import os
import posixpath
import re
import shutil
import sqlite3
import subprocess
import tempfile
import types
import urllib.parse

import apt.debfile
import apt_pkg

def ensure_cmds_exist(*cmds):
    for cmd in cmds:
        if shutil.which(cmd) is None:
            raise OSError(errno.ENOENT, 'command not found', cmd)

class Fetcher():

    def __init__(self, urlbase):
        self._urlbase = urlbase
        self._progress = apt.progress.text.AcquireProgress(sys.stderr)
        self._acquire = apt_pkg.Acquire(self._progress)
        self._files = []
        self._tmpdir = tempfile.TemporaryDirectory(prefix='lets-shrink-dbgsym.')

    def add(self, url, name):
        url = urllib.parse.urljoin(self._urlbase, url)
        self._files += [apt_pkg.AcquireFile(
            self._acquire,
            uri=url,
            descr=url,
            destfile=os.path.join(self._tmpdir.name, name)
        )]

    def run(self):
        acq = self._acquire
        rc = acq.run()
        if rc != acq.RESULT_CONTINUE:
            raise RuntimeError('fetching failed')
        for acqfile in self._files:
            if acqfile.status != acqfile.STAT_DONE:
                raise RuntimeError('fetching failed')
            yield acqfile.destfile

    def __enter__(self):
        return self

    def __exit__(self, exc, value, tb):
        self.close()

    def close(self):
        self._tmpdir.cleanup()

here = os.path.dirname(__file__)
recompress_cmd = os.path.join(here, 'dbgsym-recompress')

@dataclasses.dataclass(frozen=True)
class PkgInfo:
    size_before: int
    size_after: int
    inst_size_before: int
    inst_size_after: int

    def as_tuple(self):
        return dataclasses.astuple(self)

    def __str__(self):
        return '\t'.join(map(str, self.as_tuple()))

_inst_size_re = re.compile(r'^Installed-Size:[ \t]*([0-9]+)$', re.MULTILINE)
def get_inst_size(path):
    deb = apt.debfile.DebPackage(path)
    ctrl = deb.control_content('control')
    match = _inst_size_re.search(ctrl)
    if match is None:
        raise RuntimeError(f'{path}: missing Installed-Size')
    return int(match.group(1)) * 1024

def recompress_inplace(path):
    size_before = os.path.getsize(path)
    inst_size_before = get_inst_size(path)
    subprocess.check_call(['fakeroot', recompress_cmd, path, path])
    size_after = os.path.getsize(path)
    inst_size_after = get_inst_size(path)
    return PkgInfo(
        size_before,
        size_after,
        inst_size_before,
        inst_size_after,
    )

class DummyCache(object):

    def __getitem__(self, name):
        raise KeyError(name)

    def __setitem__(self, name, value):
        pass

    def close(self):
        pass

class SQLiteCache(object):

    def __init__(self, path):
        self.conn = sqlite3.connect(path)
        with self.conn as conn:
            conn.execute(
                '''CREATE TABLE IF NOT EXISTS "results" (
                    "name" PRIMARY KEY,
                    "size.before",
                    "size.after",
                    "inst_size.before",
                    "inst_size.after"
                )
                '''
            )

    def __getitem__(self, name):
        cursor = self.conn.cursor()
        cursor.execute('SELECT * FROM "results" WHERE "name" = ?', [name])
        row = cursor.fetchone()
        if row is None:
            raise KeyError(name)
        return PkgInfo(*row[1:])

    def __setitem__(self, name, value):
        with self.conn as conn:
            conn.execute('INSERT INTO "results" VALUES (?, ?, ?, ?, ?)',
                [name, *value.as_tuple()]
            )

    def close(self):
        self.conn.close()

default = types.SimpleNamespace(
    mirror='http://debug.mirrors.debian.org/debian-debug',
    dist='stable',
    areas='main',
    archs='amd64',
)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mirror', metavar='URL', default=default.mirror,
        help=f'Debian mirror to use (default: {default.mirror})'
    )
    ap.add_argument('--distribution', metavar='DIST', default=default.dist,
        help=f'Debian distribution to use (default: {default.dist})'
    )
    ap.add_argument('--areas', metavar='AREA[,AREA...]', default=default.areas,
        help=f'archive areas to use (default: {default.areas})'
    )
    ap.add_argument('--architectures', metavar='ARCH[,ARCH...]', default=default.archs,
        help=f'architectures to use (default: {default.archs})'
    )
    ap.add_argument('--cache', metavar='FILE',
        help='cache results in this file'
    )
    options = ap.parse_args()
    ensure_cmds_exist('fakeroot', 'dpkg', 'objcopy')
    mirror = options.mirror
    dist = options.distribution
    areas = options.areas.split(',')
    archs = options.architectures.split(',')
    urlbase = f'{mirror}/dists/{dist}-debug/'
    queue = {}
    with Fetcher(urlbase=urlbase) as fetcher:
        for area in areas:
            for arch in archs:
                path = f'{area}/binary-{arch}/Packages.xz'
                fetcher.add(path, path.replace('/', '_'))
        for pkgs_path in fetcher.run():
            for para in apt_pkg.TagFile(pkgs_path):
                path = para['Filename']
                base = posixpath.basename(path)
                queue[base] = path
    if options.cache is None:
        cache = DummyCache()
    else:
        cache = SQLiteCache(options.cache)
    for base, path in queue.items():
        try:
            info = cache[base]
        except KeyError:
            pass
        else:
            print(f'{base}\t{info}')
            sys.stdout.flush()
            continue
        with Fetcher(urlbase=f'{mirror}/') as fetcher:
            fetcher.add(path, base)
            [path] = fetcher.run()
            info = recompress_inplace(path)
            print(f'{base}\t{info}')
            sys.stdout.flush()
        cache[base] = info
    cache.close()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
