#!/bin/sh

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
UID=$(id -u)
if [ $# != 2 ]
then
    printf 'Usage: %s IN-DEB OUT-DEB\n' "${0##*/}" >&2
    exit 1
fi
if [ "$UID" -ne 0 ]
then
    printf '%s: error: must be run as (fake)root\n' "${0##*/}" >&2
    exit 1
fi
in="$1"
out="$2"
tmpdir=$(mktemp -d -t lets-shrink-dbgsym.XXXXXX)
dpkg-deb -R "$in" "$tmpdir" >&2
true > "$out"
dbgdir="$tmpdir/usr/lib/debug"
if [ -d "$dbgdir" ]
then
    find "$dbgdir" -type f -print0 \
    | xargs -0 -n1 sh -c 'objcopy --decompress-debug-sections "$@" || exit 255' -
fi
# This is not quite how dpkg-gencontrol computes Installed-Size, but hey.
tab='	'
metasize=$(du --apparent-size -k -s "$tmpdir/DEBIAN")
metasize=${metasize%${tab}**}
allsize=$(du --apparent-size -k -s "$tmpdir")
allsize=${allsize%${tab}**}
instsize=$((allsize-metasize))
sed -i -e "s/^[iI][nN][sS][tT][aA][lL][lL][eE][dD]-[sS][iI][zZ][eE]:.*\$/Installed-Size: $instsize/" "$tmpdir/DEBIAN/control"
dpkg-deb --build "$tmpdir" "$out" >&2
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
