#!/bin/sh

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
UID=$(id -u)
if [ $# != 2 ]
then
    printf 'Usage: %s IN-DEB OUT-DEB\n' "${0##*/}" >&2
    exit 1
fi
if [ "$UID" -ne 0 ]
then
    printf '%s: error: must be run as (fake)root\n' "${0##*/}" >&2
    exit 1
fi
in="$1"
out="$2"
tmpdir=$(mktemp -d -t lets-shrink-dbgsym.XXXXXX)
dpkg-deb -R "$in" "$tmpdir" >&2
true > "$out"
dbgdir="$tmpdir/usr/lib/debug"
if [ -d "$dbgdir" ]
then
    find "$dbgdir" -type f -exec objcopy --decompress-debug-sections '{}' ';'
fi
dpkg-deb --build "$tmpdir" "$out" >&2
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
